# Generated by Django 5.1.7 on 2025-04-22 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tourtag_rename_price_tour_price_per_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.tour'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.tour'),
        ),
        migrations.AddField(
            model_name='tour',
            name='season',
            field=models.CharField(choices=[('summer', 'Summer'), ('winter', 'Winter'), ('monsoon', 'Monsoon')], default='summer', max_length=10),
        ),
        migrations.DeleteModel(
            name='TourPackage',
        ),
    ]
