# Generated by Django 5.1.7 on 2025-04-23 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_review_tour_alter_booking_tour_tour_season_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TourImage',
        ),
    ]
