# Generated by Django 5.1.7 on 2025-04-24 05:48

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_tourimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='PK'),
        ),
    ]
