# Generated by Django 5.1.7 on 2025-04-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_booking_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='tags',
        ),
        migrations.DeleteModel(
            name='TourTag',
        ),
        migrations.AddField(
            model_name='tour',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
